### ISSUE TITLE
Pressing Unassign Admins,Assign Admins,Review Accounts Doesnt do anything just dummy buttons

### ISSUE THREAD

**Issue by joycetawfikmagdy** [hassaanelgarem/blackHatsReplica#12]
1. severity : high
2. reported by : Joyce Tawfik 
3. Description :  in the github repo (An error in the github code version as it was modified by the team later during our testing) after redirection using admin panel -> users-> Review Accounts, Assign Admins ,Unassign admins are just dimmy buttons do not do anything 
4. Steps :
4.1 login as admin
4.2 open admin panel - all buttons are dummies
5. Expected result : buttons should navigate to Assign Admins and Unassign admins  view so o be able to assign the user as an admin and to unassign an admin and for the review accounts it should show all the registered users on the website

**Comment by hassaanelgarem** [comment]
Working on deployed version
