### ISSUE TITLE
Pressing Review Verified Accounts ,Verify Accounts Doesnt do anything just dummy buttons 

### ISSUE THREAD

**Issue by joycetawfikmagdy** [hassaanelgarem/blackHatsReplica#17]
severity : high
2. reported by : Joyce Tawfik 
3. Description :   in the github repo (An error in the github code version as it was modified by the team later during our testing) after redirection using admin panel -> Businesses-> Review Verified Accounts, Verify Accounts are just dimmy buttons do not do anything 
4. Steps :
            4.1 login as admin
            4.2 open admin panel - all buttons are dummies
5. Expected result : buttons should navigate to Review Verified Accounts showing verified Accounts and Verify Accounts should be able to verify unverified buisnesses

**Comment by hassaanelgarem** [comment]
Working on deployed version
