### ISSUE TITLE
The Admin can't open the Advertisements page in the github repo

### ISSUE THREAD

**Issue by davidmaged** [hassaanelgarem/blackHatsReplica#21]
1. severity : high
2. reported by : David 
3. Description :  in the github repo (An error in the github code version as it was modified by the team later during our testing) after redirection using admin panel -> Advertisements is just a dummy button do not do anything 
4. Steps :
4.1 login as admin
4.2 open admin panel - Advertisements button is useless 
5. Expected result : button should navigate to Advertisements

**Comment by hassaanelgarem** [comment]
Working on deployed version
