### ISSUE TITLE
The Admin can't open Support page in the github repo

### ISSUE THREAD

**Issue by davidmaged** [hassaanelgarem/blackHatsReplica#23]
severity : high
reported by : David
Description : in the github repo (An error in the github code version as it was modified by the team later during our testing) after redirection using admin panel -> Support is just dummy button do not do anything
Steps :
4.1 login as admin
4.2 open admin panel - Support button is useless
Expected result : button should navigate to support

**Comment by hassaanelgarem** [comment]
Working on deployed version
