### ISSUE TITLE
Birth Date is not updated

### ISSUE THREAD

**Issue by MichaelAdel96** [hassaanelgarem/blackHatsReplica#8]
1.Severity : Medium
2.Reported By : Michael Adel
3.Description : When updating birthdate in user profile, an updated profile message is shown but nothing   is updated
4.Steps :
      -Log in as a user
      -Click profile then edit profile
       -Edit in Birth Date
       -Click save
       -A message shown that the profile is updated
       -The Birth Date is not updated
5.Expected Result : The Birth Date should be updated successfully

**Comment by hassaanelgarem** [comment]
It's working fine

**Comment by MichaelAdel96** [comment]
It is not working even after refresh , I know that first name and last name are working after refresh , it is a different thing

**Comment by hassaanelgarem** [comment]
<img width="1280" alt="screen shot 2017-05-02 at 12 41 24 am" src="https://cloud.githubusercontent.com/assets/25306722/25597652/49f03d96-2ed0-11e7-9d9a-56df7a47c29f.png">
Before

**Comment by hassaanelgarem** [comment]
<img width="1280" alt="screen shot 2017-05-02 at 12 41 53 am" src="https://cloud.githubusercontent.com/assets/25306722/25597662/5cb87a24-2ed0-11e7-8779-db416598ceb1.png">
After
